# Generated by Django 5.0.1 on 2025-11-30 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concessionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=64, verbose_name="Nom du concessionnaire"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                14,
                                message="Le SIRET doit contenir exactement 14 caractères.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                14,
                                message="Le SIRET doit contenir exactement 14 caractères.",
                            ),
                        ],
                        verbose_name="Numéro SIRET",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concessionnaire",
                "verbose_name_plural": "Concessionnaires",
            },
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("moto", "Moto"), ("auto", "Auto")],
                        max_length=4,
                        verbose_name="Type de véhicule",
                    ),
                ),
                ("marque", models.CharField(max_length=64, verbose_name="Marque")),
                ("chevaux", models.IntegerField(verbose_name="Puissance (chevaux)")),
                ("prix_ht", models.FloatField(verbose_name="Prix HT")),
                (
                    "concessionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="api.concessionnaire",
                        verbose_name="Concessionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
            },
        ),
    ]
